version : "3"
services:

  app:
      container_name: spring-app
      image: openjdk:11-jdk
      ports:
        - "8080:8080"
      volumes:
        - ./main:/app
      working_dir: /app
      command: [ "./gradlew", "bootrun" ]
